### PR TITLE
Support for deleting a player; and for external_player_id (alt PR)

### PR DESCRIPTION
**Pull request by reachire-smendola**
Added support for deleting a Player (required adding http DELETE command support)
Added support for `external_player_id`

Remember to assign the pull request to a [CODEOWNER](../CODEOWNERS) for review.

**ALWAYS** open PRs targeting [develop](https://github.com/mikamai/onesignal-ruby/tree/develop), as it is our mainline branch. Master is only used to cut stable releases.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have added tests for each new piece of code I added, or updated existing tests if I changed some existing code
- [x] I have added the relevant entry in the `Unreleased` section of the CHANGELOG file 
- [x] I have made corresponding changes to the documentation (namely the README file)

### CODE REVIEW

**Comment by reachire-smendola** [comment]
In attempting the rebase, I ended up renaming the branch, which closed my original PR. This is just re-submitting the same code change as in PR#34, but rebased on develop

**Review by MatteoJoliveau — APPROVED** [review]
lgtm 👍🏻 thanks!

**Comment by MatteoJoliveau** [comment]
Just released 0.6.0 with these changes 🎉 
https://github.com/mikamai/onesignal-ruby/releases/tag/0.6.0

**Comment by reachire-smendola** [comment]
Excellent! TY.,

**Pull request merged**
