### PR TITLE
Support for deleting a player; and for external_player_id

### PR DESCRIPTION
**Pull request by reachire-smendola**
Added support for deleting a Player (required adding http DELETE command support)
Added support for `external_player_id`

Remember to assign the pull request to a [CODEOWNER](../CODEOWNERS) for review.

**ALWAYS** open PRs targeting [develop](https://github.com/mikamai/onesignal-ruby/tree/develop), as it is our mainline branch. Master is only used to cut stable releases.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have added tests for each new piece of code I added, or updated existing tests if I changed some existing code
- [x] I have added the relevant entry in the `Unreleased` section of the CHANGELOG file 
- [x] I have made corresponding changes to the documentation (namely the README file)

### CODE REVIEW

**Comment by MatteoJoliveau** [comment]
Hi @reachire-smendola, thank you for your contribution! May I ask you to add some unit tests for the new features you added, as well as some example usage in the README?

**Comment by reachire-smendola** [comment]
Done!

**Review by MatteoJoliveau — APPROVED** [review]
Amazing job, thank you very much!

**Comment by MatteoJoliveau** [comment]
@reachire-smendola I just need you to rebase on develop and resolve the conflicts and then we're good to go!

**Pull request closed without merging**
